#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long qw(GetOptions);
use File::Basename qw(dirname);
use File::Path qw(make_path);

my $default_path = '';
my $input_path = '';
my $output_path = '';
my $emit_mk = '';

GetOptions(
    'default=s' => \$default_path,
    'in=s'      => \$input_path,
    'out=s'     => \$output_path,
    'mk=s'      => \$emit_mk,
) or die "usage: merge-config.pl --default defaults.config [--in .config] --out .config [--mk config.mk]\n";

die "--default is required\n" if $default_path eq '';
die "--out is required\n" if $output_path eq '';

sub trim {
    my ($value) = @_;
    $value =~ s/^\s+//;
    $value =~ s/\s+$//;
    return $value;
}

sub unquote_value {
    my ($value) = @_;

    $value = trim($value);

    if ($value =~ /^"(.*)"$/s) {
        $value = $1;
        $value =~ s/\\n/\n/g;
        $value =~ s/\\t/\t/g;
        $value =~ s/\\"/"/g;
        $value =~ s/\\\\/\\/g;
    }

    return $value;
}

sub config_quote {
    my ($value) = @_;

    if ($value =~ /^[A-Za-z0-9_.:+\/-]+$/) {
        return $value;
    }

    $value =~ s/\\/\\\\/g;
    $value =~ s/"/\\"/g;
    $value =~ s/\n/\\n/g;
    $value =~ s/\t/\\t/g;

    return "\"$value\"";
}

sub read_config {
    my ($path, $required) = @_;
    my %values;
    my @order;

    if ($path eq '' || !-f $path) {
        die "config not found: $path\n" if $required;
        return (\%values, \@order);
    }

    open my $fh, '<', $path or die "open $path: $!\n";

    while (my $line = <$fh>) {
        chomp $line;

        next if $line =~ /^\s*$/;
        next if $line =~ /^\s*#/;

        if ($line =~ /^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$/) {
            my ($key, $value) = ($1, $2);

            $value = unquote_value($value);

            push @order, $key if !exists $values{$key};
            $values{$key} = $value;
            next;
        }

        die "invalid config line in $path: $line\n";
    }

    close $fh;

    return (\%values, \@order);
}

sub validate_bool {
    my ($key, $value) = @_;

    die "$key must be y or n\n" if $value ne 'y' && $value ne 'n';
}

sub validate_positive_integer {
    my ($key, $value) = @_;

    die "$key must be a positive integer\n" if $value !~ /^[1-9][0-9]*$/;
}

sub validate_non_empty {
    my ($key, $value) = @_;

    die "$key must not be empty\n" if $value eq '';
}

sub validate_value {
    my ($key, $value) = @_;

    if ($key =~ /^IMAGE_.*_SIZE_MB$/) {
        validate_positive_integer($key, $value);
        return;
    }

    if ($key =~ /^(ARCH_X86_64|ENABLE_SMP|ENABLE_KPTI|ENABLE_ASLR)$/) {
        validate_bool($key, $value);
        return;
    }

    if ($key =~ /^(USER_BUILD_SELFTESTS|USER_BUILD_MPK_SAMPLES)$/) {
        validate_bool($key, $value);
        return;
    }

    if ($key =~ /^(DRIVER_XHCI|DRIVER_I8042|DRIVER_VIRTIO_NET)$/) {
        validate_bool($key, $value);
        return;
    }

    if ($key =~ /^(DEBUG_QEMU_GUI|DEBUG_QEMU_DEBUG|DEBUG_QEMU_KVM)$/) {
        validate_bool($key, $value);
        return;
    }

    if ($key =~ /^(KERNEL_RUST_TOOLCHAIN|USER_RUST_STD_TOOLCHAIN)$/) {
        validate_non_empty($key, $value);
        return;
    }
}

sub write_if_changed {
    my ($path, $content) = @_;

    if (-f $path) {
        open my $existing_fh, '<', $path or die "open $path: $!\n";
        local $/;
        my $existing = <$existing_fh> // '';
        close $existing_fh;
        return if $existing eq $content;
    }

    open my $fh, '>', $path or die "open $path: $!\n";
    print {$fh} $content;
    close $fh;
}

my ($defaults, $default_order) = read_config($default_path, 1);
my ($input, undef) = read_config($input_path, 0);

my %merged = %{$defaults};

for my $key (sort keys %{$input}) {
    if (!exists $defaults->{$key}) {
        warn "warning: unknown config $key ignored\n";
        next;
    }

    $merged{$key} = $input->{$key};
}

for my $key (@{$default_order}) {
    validate_value($key, $merged{$key});
}

make_path(dirname($output_path));

my $output = "# Automatically generated by scripts/config/merge-config.pl\n";
$output .= "# Edit this file or run make olddefconfig after changing defaults.\n\n";

for my $key (@{$default_order}) {
    $output .= "$key=" . config_quote($merged{$key}) . "\n";
}
write_if_changed($output_path, $output);

if ($emit_mk ne '') {
    make_path(dirname($emit_mk));

    my $make_output = "# Automatically generated. Do not edit.\n";

    for my $key (@{$default_order}) {
        $make_output .= "$key := $merged{$key}\n";
    }
    write_if_changed($emit_mk, $make_output);
}
