#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long qw(GetOptions);
use File::Basename qw(dirname);
use File::Path qw(make_path);

my $default_path = '';
my $input_path = '';
my $output_path = '';
my $emit_mk = '';
my $emit_env = '';

GetOptions(
    'default=s' => \$default_path,
    'in=s'      => \$input_path,
    'out=s'     => \$output_path,
    'mk=s'      => \$emit_mk,
    'env=s'     => \$emit_env,
) or die "usage: merge-config.pl --default defaults.config [--in .config] --out .config [--mk config.mk] [--env config.env]\n";

die "--default is required\n" if $default_path eq '';
die "--out is required\n" if $output_path eq '';

sub read_config {
    my ($path, $required) = @_;
    my %values;
    my @order;

    if (!-f $path) {
        die "config not found: $path\n" if $required;
        return (\%values, \@order);
    }

    open my $fh, '<', $path or die "open $path: $!\n";
    while (my $line = <$fh>) {
        chomp $line;
        next if $line =~ /^\s*$/;
        next if $line =~ /^\s*#/;
        if ($line =~ /^\s*(CONFIG_[A-Za-z0-9_]+)=(.*)\s*$/) {
            my ($key, $value) = ($1, $2);
            $value =~ s/\s+$//;
            push @order, $key if !exists $values{$key};
            $values{$key} = $value;
            next;
        }
        die "invalid config line in $path: $line\n";
    }
    close $fh;

    return (\%values, \@order);
}

sub validate_value {
    my ($key, $value) = @_;
    if ($key =~ /_(SIZE_MB)$/) {
        die "$key must be a positive integer\n" if $value !~ /^[1-9][0-9]*$/;
        return;
    }
    if ($key =~ /^CONFIG_(XHCI|I8042|QEMU_GUI|QEMU_DEBUG|BUILD_SELFTESTS|BUILD_MPK_SAMPLES)$/) {
        die "$key must be y or n\n" if $value ne 'y' && $value ne 'n';
        return;
    }
    if ($key =~ /^CONFIG_(KERNEL_TOOLCHAIN|RUST_STD_TOOLCHAIN)$/) {
        die "$key must not be empty\n" if $value eq '';
        return;
    }
}

sub shell_quote {
    my ($value) = @_;
    $value =~ s/'/'"'"'/g;
    return "'$value'";
}

my ($defaults, $default_order) = read_config($default_path, 1);
my ($input, undef) = read_config($input_path, 0);

my %merged = %{$defaults};
for my $key (sort keys %{$input}) {
    warn "warning: unknown config $key ignored\n" if !exists $defaults->{$key};
    next if !exists $defaults->{$key};
    $merged{$key} = $input->{$key};
}

for my $key (@{$default_order}) {
    validate_value($key, $merged{$key});
}

make_path(dirname($output_path));
open my $out, '>', $output_path or die "open $output_path: $!\n";
print {$out} "# Automatically generated by scripts/config/merge-config.pl\n";
print {$out} "# Edit this file or run make olddefconfig after changing defaults.\n\n";
for my $key (@{$default_order}) {
    print {$out} "$key=$merged{$key}\n";
}
close $out;

if ($emit_mk ne '') {
    make_path(dirname($emit_mk));
    open my $mk, '>', $emit_mk or die "open $emit_mk: $!\n";
    print {$mk} "# Automatically generated. Do not edit.\n";
    for my $key (@{$default_order}) {
        print {$mk} "$key := $merged{$key}\n";
    }
    close $mk;
}

if ($emit_env ne '') {
    make_path(dirname($emit_env));
    open my $env, '>', $emit_env or die "open $emit_env: $!\n";
    print {$env} "# Automatically generated. Do not edit.\n";
    for my $key (@{$default_order}) {
        print {$env} "export $key=", shell_quote($merged{$key}), "\n";
    }
    close $env;
}
