version = 1
id = "2d001ceb0b2aea71d13c5b07"
created = "2026-08-03T10:48:56.422031253+09:00"

[trigger]
name = "mochiOS/syscalls"
path = "user"
repository = "/home/jnix/mochiOS/user"
head = "e00e535b543a462f89ba77a935327328ad775161"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "chore: refresh dependency lockfile"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "1a18b8a5885dbb7e8d2ed85a6087fe59d7e915e4"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "26fda999d6a2162b39bd51100ec00145ace585b4"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "e00e535b543a462f89ba77a935327328ad775161"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "eecdc96fcabcb2b8852a91bfa572623d335827c3"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "87c49950042c8db97e520e6f0fbb60aba2ddef72"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "cea09a39e3fc922dc540364df28695ede9b3c690"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "c5fb7a6e7da7327bea8f9eb7d8b29fc9a02b3c56"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "349d5519d5370c4b3a079404b968589daf849fd8"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "cb52345fa7f01bb0942741a0e843e39037e371e2"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "ee3e56d8248225a535a9c105d2b7bbdf69a689dd"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "59c576e16a4ea598bda6ab228e4f4b9b55b1551b"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "e1b9701b9417bab47e25a0396acc3a99b268fbb1"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "182e3052b8722b74742b2bec1dc46615bf9c2eae"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "20f522a181693e76ae90169bc0c4ac3d51738cbc"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "991b0cdc0e20d27dd90c497a3abaa0dd98e749fa"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "bd13ee9f19a5a7fce4740902eba8999f9736642b"

[[projects]]
name = "mochiOS/Terminal"
path = "applications/terminal"
head = "7bb02726284f6b029f9eb64abaa11488f401b8a0"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "8f980d22783256591215fbd50f1e5eebf880dd25"

[[projects]]
name = "mochiOS/Files.app"
path = "applications/file"
head = "6206c9197a47bd99a97cedce1cc4c22f4c43f648"
