version = 1
id = "2e867e5fbf99f9fbfcaee2dc"
created = "2026-07-14T18:12:32.367539949+09:00"

[trigger]
name = "mochiOS/mws"
path = "tools/mws"
repository = "/home/jine/Develop/mochiOS/tools/mws"
head = "bd8e69e7ba0f0aa1f480cce19c62faf4dae197e3"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "restore latestを実装"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "741a33bacd27c8d02352a7e3dac9512ec1351d19"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "3d6ce2590b3e42ae978c3ac0a1ee474c4fa4f707"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "9e6659a2e2b859d92fe1a59d5b1b40877a679586"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "02fc2a45d64caa6239dbc867f954af62ddc9eaca"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "c5db5491c5530031afc9908cbda0daba1f7fa127"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "f2028b0f0f6c447ee5625f0be551ff41d2927963"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "1a651fdb3c08e46b988f149b7b206798abc2bc82"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "7fcdfebcba89c2bd313c8700efd10db62c907cdd"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "fa1cabc29037f3aea7ecd470e6fc361b4afcb1ac"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "1d801086ef3f65dce472fbf2a20258bf92aa72a7"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "b24869ca6612e2f5391725a37d15611426b261af"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "7fb3761b074c18b9cda87fded66d74bfe795a99f"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "f4e13d0d738b4306b51b9ee211a780daccb92651"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "4d8cb6dfe12587a93d25eb180694bc297dd2a0bd"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "5d089901381e5f717ad387750cd220b38b4cf447"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "78b57c14de2ebc6e965f78d4afafd1fc4eeb7591"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "bd8e69e7ba0f0aa1f480cce19c62faf4dae197e3"
