version = 1
id = "50e4ad7c02a2cc14dfd60015"
created = "2026-08-01T18:28:19.738977103+09:00"

[trigger]
name = "mochiOS/buildtools"
path = "build"
repository = "/home/jnix/mochiOS/build"
head = "e610be119ad4dbbae272604b32fb104514de5ede"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "build: pin compatible userland Rust toolchain"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "1a18b8a5885dbb7e8d2ed85a6087fe59d7e915e4"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "758c46dc392577297f60b95dd3cbba891a434a00"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "01bf54f70c750e3a2ed0e0b183dd93a3e2bee934"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "6fe388e2ad989625dbc067c7b3e7ebc5c6f62eb4"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "be32b0c40c557e3881eb6f74c8839c407e3440fb"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "cea09a39e3fc922dc540364df28695ede9b3c690"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "c5fb7a6e7da7327bea8f9eb7d8b29fc9a02b3c56"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "7a585153c0fab05ed14c66e53a7f7229c6a3e050"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "94f53c5a1c476c5df2456d880dbdc110eb9344bd"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "cf695304e6397612c070298eaff1e2ed2f26ab7f"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "be135b922ada8ffe570a33dfc73d93e360d0cac5"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "e0c39d78852c13a1e861c8f0c7143a77ceff638f"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "9ed9fc382321aac65993a43929f68da4243cc99b"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "e610be119ad4dbbae272604b32fb104514de5ede"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "657320d0fca78a5461e66640e14d43ccebdf5470"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "bd13ee9f19a5a7fce4740902eba8999f9736642b"

[[projects]]
name = "mochiOS/Terminal"
path = "applications/terminal"
head = "5cc0c30e36e256267801831c6370a31f31b6a7a2"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "8f980d22783256591215fbd50f1e5eebf880dd25"

[[projects]]
name = "mochiOS/Files.app"
path = "applications/file"
head = "6206c9197a47bd99a97cedce1cc4c22f4c43f648"
