version = 1
id = "57b8b41b7a69730cf373e8df"
created = "2026-07-14T17:54:48.446412059+09:00"

[trigger]
name = "mochiOS/mws"
path = "tools/mws"
repository = "/home/jine/Develop/mochiOS/tools/mws"
head = "2f3bbe76cdaa77ebd912b948e0f44adc1f8ec7aa"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "リファクタ"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "741a33bacd27c8d02352a7e3dac9512ec1351d19"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "3d6ce2590b3e42ae978c3ac0a1ee474c4fa4f707"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "9b429a3c5a9f2fea28939029ba8740d3e90324b7"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "67a8ac56cbb52452661f855add00e41177917e46"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "c5db5491c5530031afc9908cbda0daba1f7fa127"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "f2028b0f0f6c447ee5625f0be551ff41d2927963"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "4c0fc56cad9d39afbacebcc58d2174d1af131b2c"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "7fcdfebcba89c2bd313c8700efd10db62c907cdd"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "fa1cabc29037f3aea7ecd470e6fc361b4afcb1ac"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "1d801086ef3f65dce472fbf2a20258bf92aa72a7"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "b24869ca6612e2f5391725a37d15611426b261af"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "7fb3761b074c18b9cda87fded66d74bfe795a99f"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "baf350d7d5d0aba88a0e05baffac546a48a17f84"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "4d8cb6dfe12587a93d25eb180694bc297dd2a0bd"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "5d089901381e5f717ad387750cd220b38b4cf447"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "78b57c14de2ebc6e965f78d4afafd1fc4eeb7591"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "2f3bbe76cdaa77ebd912b948e0f44adc1f8ec7aa"
