version = 1
id = "82b5cd62a710a2c5e848f8f6"
created = "2026-08-01T11:37:42.889225764+09:00"

[trigger]
name = "mochiOS/syscalls"
path = "user"
repository = "/home/jnix/mochiOS/user"
head = "b48c44c12918797000aa925fecca08ad3e9f3c3d"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "refactor: move user test files under tmp"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "1a18b8a5885dbb7e8d2ed85a6087fe59d7e915e4"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "edc815621636b09886ac7514391838ede020014a"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "b48c44c12918797000aa925fecca08ad3e9f3c3d"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "c325c938f9d67e45e017dc9f90a2a0de8625e655"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "863838ead8f346a65b5bd1a59415f2316dc83b28"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "cea09a39e3fc922dc540364df28695ede9b3c690"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "6f47864214658e3bb31776eded6dfd44c3237bb6"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "7a585153c0fab05ed14c66e53a7f7229c6a3e050"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "d2072c233a70c5044bc9adc1d6c60cafc3e663e1"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "cf695304e6397612c070298eaff1e2ed2f26ab7f"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "8d4eb776f0b80cccc3841d933f819c9d23477205"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "b0bce828360221467aef73f1d4d3d31745bac696"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "18123ca43084ecce3f901d6afe3f0344f677e23c"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "52bf4836a1f33afdd1e81f8fd3e78901f26da991"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "657320d0fca78a5461e66640e14d43ccebdf5470"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "bd13ee9f19a5a7fce4740902eba8999f9736642b"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "8f980d22783256591215fbd50f1e5eebf880dd25"
