version = 1
id = "8a157623cb53e692b253d799"
created = "2026-08-30T13:50:59.427818073+09:00"

[trigger]
name = "mochiOS/devkit"
path = "tools/devkit"
repository = "/home/jnix/mochiOS/tools/devkit"
head = "2e1f8c55245394ca9909a7d400545cb961d177b7"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "Refresh development trust fixtures"

[[projects]]
name = "mochiOS/mBoot"
path = "mboot"
head = "ca581b68257eb54a4c0a5e7d65aea8d05a595e4f"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "b68d96a04d330bf0cbead97f5c75c945ffd35cb9"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "9f098f219b927786f81c7b60a31f82854d7f54ec"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "97725aca92f3fb76b9cea222573758cd3bcf960b"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "6ea09ebe94ccf357104548a4305a91d32415dde3"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "2b0ffd2bf2e279e309910e5dfc53ac4acdf9399e"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "cea09a39e3fc922dc540364df28695ede9b3c690"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "c5fb7a6e7da7327bea8f9eb7d8b29fc9a02b3c56"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "349d5519d5370c4b3a079404b968589daf849fd8"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "cb52345fa7f01bb0942741a0e843e39037e371e2"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "f35082dbdb14a5582ec211331dace10777e3112b"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "89cd514f27eea49b531fe8d261449c3b31941867"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "55de3a63039ff560f6ae309969dc61f9717375ca"

[[projects]]
name = "mochiOS/Installer.app"
path = "applications/installer"
head = "01066badcddf43626746a08592286eead67baad8"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "c4f1ebf675acd4f7e38330c9f9d64cd5718da239"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "cae58a02d39fa23ff4d624c2d53aa9d9c9fed303"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "2d6d2340343f7ab10452b483d855da984087af8e"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "bd13ee9f19a5a7fce4740902eba8999f9736642b"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "2e1f8c55245394ca9909a7d400545cb961d177b7"

[[projects]]
name = "mochiOS/Terminal"
path = "applications/terminal"
head = "3070d37501be228621175b915274a84e84bd23d7"

[[projects]]
name = "mochiOS/Files.app"
path = "applications/file"
head = "bf8b63de54a1e85a4fb2d2370a18b310cb02491a"

[[projects]]
name = "mochiOS/Settings.app"
path = "applications/settings"
head = "40bbf56bbe50c696afd8788eed1dcc76410ca5db"
