version = 1
id = "951167999559b83027b81577"
created = "2026-07-26T21:15:42.549954105+09:00"

[trigger]
name = "mochiOS/buildtools"
path = "build"
repository = "/home/jnix/mochiOS/build"
head = "6b9a4b58c458aed3928e3d81d4c7484990aad7a9"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "build: enable virtio network driver"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "45c2c544362a1fa95ad59432f0a2777e620fa024"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "9b2ff804adb7a243d73f7fec68eca7c9d2888f37"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "fa5cbc0a9fac5e98800384d4008ac6eae4233479"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "d68d667b923f0440a0940dd1561df25ee1559c50"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "ff8d6a47525aaff8bed6e7073df754d41181d91d"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "e75641271d1b425bd7a5e04aac94396abaf7c230"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "6f47864214658e3bb31776eded6dfd44c3237bb6"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "7a585153c0fab05ed14c66e53a7f7229c6a3e050"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "d2072c233a70c5044bc9adc1d6c60cafc3e663e1"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "a3004abb6a3126bec2e67489b63e9cc446ea9016"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "cda13dd89c1cd85a18975a18017324db1e8bbf3e"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "326bebf652d17d912bb799ae7008a58b9cc97f52"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "7bb0b5d6b0d2be17a738da10bd1bf0c2bdab8d88"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "6b9a4b58c458aed3928e3d81d4c7484990aad7a9"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "657320d0fca78a5461e66640e14d43ccebdf5470"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "1830eeeb35f08b6c0d4050adc052f06d807b1c9d"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "806389950d548d4da443a2cf151a398b2e81da6a"
