version = 1
id = "a40081c496eb0809e56a7508"
created = "2026-08-20T10:34:34.905901601+09:00"

[trigger]
name = "mochiOS/mBoot"
path = "mboot"
repository = "/home/jnix/mochiOS/mboot"
head = "e2c194a104f49b0a1537a6669de413e10bba3caa"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "fix: reset DHCP state on Wi-Fi changes"

[[projects]]
name = "mochiOS/mBoot"
path = "mboot"
head = "e2c194a104f49b0a1537a6669de413e10bba3caa"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "1a18b8a5885dbb7e8d2ed85a6087fe59d7e915e4"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "ddc1530f42df420cc448d0fed7f8d0e89b6d12aa"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "5ae75b9104ca195d16e154e7d058503208f97044"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "1fc7f92d47288ded47c6fabc8a1f768f3e0fb19c"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "aaaf38d2120bb2b2024741746ed5339b59053895"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "cea09a39e3fc922dc540364df28695ede9b3c690"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "c5fb7a6e7da7327bea8f9eb7d8b29fc9a02b3c56"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "349d5519d5370c4b3a079404b968589daf849fd8"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "cb52345fa7f01bb0942741a0e843e39037e371e2"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "e02f5fb619b0dfd0e6660dacce4d64c3fe9c00e4"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "f8bf3ab6dfc04d505f4234a64791ed2789eaf0de"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "04738bef0f8c206fbe82471bdd560f8096723070"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "9f566e4ffaa94cb8e0e58776327389bdecdb6541"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "ae7d24056fa620791c2e7e545f66005dbe5f2589"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "2ab096f8631949fbaf043241ce28490a0d54bd57"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "bd13ee9f19a5a7fce4740902eba8999f9736642b"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "6da4965d8c0c8a0317c6c3437b1a6ad13739acb9"

[[projects]]
name = "mochiOS/Terminal"
path = "applications/terminal"
head = "3070d37501be228621175b915274a84e84bd23d7"

[[projects]]
name = "mochiOS/Files.app"
path = "applications/file"
head = "23addcf87c0ffc8199443fd676fd24775edfdc4b"

[[projects]]
name = "mochiOS/Settings.app"
path = "applications/settings"
head = "40bbf56bbe50c696afd8788eed1dcc76410ca5db"
