version = 1
id = "bf790440e5560d3b3746b963"
created = "2026-09-02T17:28:01.320222985+09:00"

[trigger]
name = "mochiOS/mnu"
path = "core"
repository = "/home/jnix/mochiOS/core"
head = "354d1416247ea4cf318fb7d612f5370025ec8a60"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "Test frame allocation rollback"

[[projects]]
name = "mochiOS/mBoot"
path = "mboot"
head = "1d36228a0be88af36ef87d388364c1f0c5d47f2c"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "2d9b16f6ec9e32b9e9cb1a40dfed0d45be4deb7f"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "354d1416247ea4cf318fb7d612f5370025ec8a60"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "e3e8d7264c28b28da8b5e608a15164d544844e26"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "474763db62826d8461df15f61dfe5b2c387b1886"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "2b0ffd2bf2e279e309910e5dfc53ac4acdf9399e"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "cea09a39e3fc922dc540364df28695ede9b3c690"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "c5fb7a6e7da7327bea8f9eb7d8b29fc9a02b3c56"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "349d5519d5370c4b3a079404b968589daf849fd8"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "cb52345fa7f01bb0942741a0e843e39037e371e2"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "f35082dbdb14a5582ec211331dace10777e3112b"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "d28bb6001d3d6653a832334fb380a33586ca4938"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "dfbd8fc7dd706e93cf1922ed3e71b519a8575ba0"

[[projects]]
name = "mochiOS/Installer.app"
path = "applications/installer"
head = "60a3290bbccda58b4ad40f9b281c271e36395d5e"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "c4f1ebf675acd4f7e38330c9f9d64cd5718da239"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "faf13aaa596e676668a5485f29ee3ec9d5223a9e"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "2d6d2340343f7ab10452b483d855da984087af8e"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "bd13ee9f19a5a7fce4740902eba8999f9736642b"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "2e1f8c55245394ca9909a7d400545cb961d177b7"

[[projects]]
name = "mochiOS/Terminal"
path = "applications/terminal"
head = "3070d37501be228621175b915274a84e84bd23d7"

[[projects]]
name = "mochiOS/Files.app"
path = "applications/file"
head = "bf8b63de54a1e85a4fb2d2370a18b310cb02491a"

[[projects]]
name = "mochiOS/Settings.app"
path = "applications/settings"
head = "40bbf56bbe50c696afd8788eed1dcc76410ca5db"
