version = 1
id = "c38a0e51f3e34d59b84603ba"
created = "2026-08-12T11:25:58.054654967+09:00"

[trigger]
name = "mochiOS/syscalls"
path = "user"
repository = "/home/jnix/mochiOS/user"
head = "2f3c88c70470fc78867a138a947f7cd9a51c3186"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "protocol: add Linux filesystem portal grants"

[[projects]]
name = "mochiOS/mBoot"
path = "mboot"
head = "78fe5f5122a707b812b7024495a29a828d598644"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "1a18b8a5885dbb7e8d2ed85a6087fe59d7e915e4"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "4d49e9c649abbedc888773d75f01c1fae3840c5d"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "2f3c88c70470fc78867a138a947f7cd9a51c3186"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "75ce40fb58e292b7b9bc3dbbc9d970a80b86b0c8"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "87c49950042c8db97e520e6f0fbb60aba2ddef72"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "cea09a39e3fc922dc540364df28695ede9b3c690"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "c5fb7a6e7da7327bea8f9eb7d8b29fc9a02b3c56"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "349d5519d5370c4b3a079404b968589daf849fd8"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "cb52345fa7f01bb0942741a0e843e39037e371e2"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "16914249a93641874aae51b2b331adf6ed583a4b"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "1addbead0538b4f799e467ff2d24b914db0f6a9b"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "f78125d3858e48d8abde8f29ac90bfc9f5617e41"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "4235c6e3f583671ff1b6a60fd7f9bae51d27d0f9"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "ca619ac7aac226aa1fcc85314230694c48f092f6"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "2a080e8179d722c558163c8fcacb090ddb40a8de"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "bd13ee9f19a5a7fce4740902eba8999f9736642b"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "db4a6ebd8a3cca0fb65a223afa04ac334811c623"

[[projects]]
name = "mochiOS/Terminal"
path = "applications/terminal"
head = "75cf031638f3adc31101fe55d4bfd37813379c62"

[[projects]]
name = "mochiOS/Files.app"
path = "applications/file"
head = "23addcf87c0ffc8199443fd676fd24775edfdc4b"

[[projects]]
name = "mochiOS/Settings.app"
path = "applications/settings"
head = "6fae85448bce0a9c944d3da1fd458948cc31355f"
