version = 1
id = "d49a4f5a2fcbb6951118222d"
created = "2026-07-14T19:15:09.772096932+09:00"

[trigger]
name = "mochiOS/syscalls"
path = "user"
repository = "/home/jine/Develop/mochiOS/user"
head = "91fd4503577d6c74aa18a0690af239c5028c2c25"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "fix libc"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "741a33bacd27c8d02352a7e3dac9512ec1351d19"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "3d6ce2590b3e42ae978c3ac0a1ee474c4fa4f707"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "91fd4503577d6c74aa18a0690af239c5028c2c25"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "02fc2a45d64caa6239dbc867f954af62ddc9eaca"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "c5db5491c5530031afc9908cbda0daba1f7fa127"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "f2028b0f0f6c447ee5625f0be551ff41d2927963"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "1a651fdb3c08e46b988f149b7b206798abc2bc82"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "7fcdfebcba89c2bd313c8700efd10db62c907cdd"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "a938cd3dc94dd0480d23a42986cece950f6c7ff3"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "1d801086ef3f65dce472fbf2a20258bf92aa72a7"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "b24869ca6612e2f5391725a37d15611426b261af"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "1b00a17fae897bcbfcf1f4104a989f28671476dd"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "84c83173932cddceb66af796236ddd107f3d0093"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "4d8cb6dfe12587a93d25eb180694bc297dd2a0bd"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "41492aa7ecbfd4602da814fbcb9fd3cbf8c88ff6"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "78b57c14de2ebc6e965f78d4afafd1fc4eeb7591"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "696b66e0a8589ff2b957b5fbce1e193f37a2082d"
