version = 1
id = "d4d18d0b6a90f4758a8af9ab"
created = "2026-07-15T17:26:36.888130985+09:00"

[trigger]
name = "mochiOS/libc"
path = "libraries/libc"
repository = "/home/jnix/mochiOS/libraries/libc"
head = "4427f76efdf92eb05b3e0b824ef90120ca587f6d"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "fix"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "741a33bacd27c8d02352a7e3dac9512ec1351d19"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "d0058943ff0a9aa58a5ceb524e43c919eae6f66c"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "9e6659a2e2b859d92fe1a59d5b1b40877a679586"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "ab31a9611402a45bbac22e201d04885b6060ab8b"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "c5db5491c5530031afc9908cbda0daba1f7fa127"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "f2028b0f0f6c447ee5625f0be551ff41d2927963"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "6f47864214658e3bb31776eded6dfd44c3237bb6"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "7fcdfebcba89c2bd313c8700efd10db62c907cdd"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "4427f76efdf92eb05b3e0b824ef90120ca587f6d"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "61e598776bf08ac5c9176d5a7777e2161386cbd8"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "b24869ca6612e2f5391725a37d15611426b261af"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "24893888a85d8aac032fea7b9ebfc52aa5dc6710"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "84c83173932cddceb66af796236ddd107f3d0093"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "4d8cb6dfe12587a93d25eb180694bc297dd2a0bd"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "41492aa7ecbfd4602da814fbcb9fd3cbf8c88ff6"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "78b57c14de2ebc6e965f78d4afafd1fc4eeb7591"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "7d38337802887afa7ca7294c9b94df9d6832b103"
