version = 1
id = "e2f65b6836b1d683aa141e2d"
created = "2026-07-29T16:29:07.058989588+09:00"

[trigger]
name = "mochiOS/Binder"
path = "applications/binder"
repository = "/home/jnix/mochiOS/applications/binder"
head = "53d224e360279c577d2985674cc65654ee41d375"
author = "tas0dev <156896971+tas0dev@users.noreply.github.com>"
message = "fix"

[[projects]]
name = "mochiOS/boot"
path = "boot"
head = "1a18b8a5885dbb7e8d2ed85a6087fe59d7e915e4"

[[projects]]
name = "mochiOS/mnu"
path = "core"
head = "7460aa5cf1a12f4c69735644601775c38dcf21be"

[[projects]]
name = "mochiOS/syscalls"
path = "user"
head = "6c7cc7379aa8cf827b009d9da5923c3f8b3f9b39"

[[projects]]
name = "mochiOS/services"
path = "services"
head = "52e1ff9825e9ff42edf2e64ec4ad00d4ff389886"

[[projects]]
name = "mochiOS/cexts"
path = "cexts"
head = "863838ead8f346a65b5bd1a59415f2316dc83b28"

[[projects]]
name = "mochiOS/drivers"
path = "drivers"
head = "1c0783b67c9c22df7210ce2dc33c5041066eac3f"

[[projects]]
name = "newlib-cygwin"
path = "libraries/newlib"
head = "6f47864214658e3bb31776eded6dfd44c3237bb6"

[[projects]]
name = "mochiOS/rust"
path = "libraries/rust"
head = "7a585153c0fab05ed14c66e53a7f7229c6a3e050"

[[projects]]
name = "mochiOS/libc"
path = "libraries/libc"
head = "d2072c233a70c5044bc9adc1d6c60cafc3e663e1"

[[projects]]
name = "mochiOS/msh"
path = "binaries/msh"
head = "3d0de0ad3372b93ad5b28094fe3ad0d7709fdff4"

[[projects]]
name = "mochiOS/coreutils"
path = "binaries/coreutils"
head = "3bbc92ae8b13f0cdc4a6682d742f5f5634ec5663"

[[projects]]
name = "mochiOS/Binder"
path = "applications/binder"
head = "53d224e360279c577d2985674cc65654ee41d375"

[[projects]]
name = "mochiOS/ViewKit"
path = "libraries/viewkit"
head = "28e1dc99096b281105066ea0b821ad02499824ad"

[[projects]]
name = "mochiOS/buildtools"
path = "build"
head = "2f1977edc8e673acc2fd1a67275b2842a8e9e17e"

[[projects]]
name = "mochiOS/test-application"
path = "applications/test.app"
head = "657320d0fca78a5461e66640e14d43ccebdf5470"

[[projects]]
name = "mochiOS/fonts"
path = "libraries/fonts"
head = "e34529b27589b2415352925d186661dc07327ea1"

[[projects]]
name = "mochiOS/mws"
path = "tools/mws"
head = "1830eeeb35f08b6c0d4050adc052f06d807b1c9d"

[[projects]]
name = "mochiOS/devkit"
path = "tools/devkit"
head = "f74a178781f38ca6dc7f18d80c57f635f8fb422a"
